light wakeup:
  - platform: mqtt_json
    name: "WakeupLight"
    state_topic: "ledstrip/wakeup"
    command_topic: "ledstrip/wakeup/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
